### ISSUE TITLE
error: failed to run custom build command for `bpf-sys v2.1.0

### ISSUE THREAD

**Issue by jitendraky** [foniod/redbpf#222]
error: failed to run custom build command for `bpf-sys v2.1.0 (/home/aviator/src/redbpf/bpf-sys)`

Caused by:
  process didn't exit successfully: `/home/aviator/src/redbpf/target/debug/build/bpf-sys-abaa06473432f5b6/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=native=/home/aviator/src/redbpf/target/debug/build/bpf-sys-084f30a3b212853f/out
  cargo:rustc-link-lib=static=bpf
  cargo:rustc-link-lib=elf
  cargo:rustc-link-lib=z
  cargo:rerun-if-changed=libbpf/
  cargo:rerun-if-changed=bpfsys-musl.h
  cargo:rerun-if-changed=libbpf_xdp.h
  make: Entering directory '/home/aiotor/src/redbpf/bpf-sys/libbpf/src'
  make: Leaving directory '/home/aiotor/src/redbpf/bpf-sys/libbpf/src'

  --- stderr
  make: *** No rule to make target 'install'.  Stop.
  thread 'main' panicked at 'failed to build `libbpf` static library', bpf-sys/build.rs:56:9
  stack backtrace:
     0:     0x55c28ad814dc - std::backtrace_rs::backtrace::libunwind::trace::h3fea1eb2e0ba2ac9
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
     1:     0x55c28ad814dc - std::backtrace_rs::backtrace::trace_unsynchronized::h849d83492cbc0d59
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55c28ad814dc - std::sys_common::backtrace::_print_fmt::he3179d37290f23d3
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:67:5
     3:     0x55c28ad814dc - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h140f6925cad14324
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:46:22
     4:     0x55c28ada693c - core::fmt::write::h31b9cd1bedd7ea38
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/fmt/mod.rs:1150:17
     5:     0x55c28ad7e1d5 - std::io::Write::write_fmt::h1fdf66f83f70913e
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/io/mod.rs:1667:15
     6:     0x55c28ad83250 - std::sys_common::backtrace::_print::he7ac492cd19c3189
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:49:5
     7:     0x55c28ad83250 - std::sys_common::backtrace::print::hba20f8920229d8e8
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:36:9
     8:     0x55c28ad83250 - std::panicking::default_hook::{{closure}}::h714d63979ae18678
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:210:50
     9:     0x55c28ad82e07 - std::panicking::default_hook::hf1afb64e69563ca8
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:227:9
    10:     0x55c28ad83904 - std::panicking::rust_panic_with_hook::h02231a501e274a13
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:624:17
    11:     0x55c28ad28f92 - std::panicking::begin_panic::{{closure}}::hee4deedc64ec9f1b
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:544:9
    12:     0x55c28ad1b8a9 - std::sys_common::backtrace::__rust_end_short_backtrace::h31d11e2c26b45a27
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:141:18
    13:     0x55c28ad28ed3 - std::panicking::begin_panic::he914f3ad9889f492
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:543:12
    14:     0x55c28a859c4a - build_script_build::main::hec755e2d87f0b62c
                                 at /home/aiotor/src/redbpf/bpf-sys/build.rs:56:9
    15:     0x55c28a85ca1b - core::ops::function::FnOnce::call_once::h91d655575cf2eddd
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:227:5
    16:     0x55c28a85a77e - std::sys_common::backtrace::__rust_begin_short_backtrace::hd29418397f88ac8d
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/sys_common/backtrace.rs:125:18
    17:     0x55c28a85d181 - std::rt::lang_start::{{closure}}::hfb80d0c6d9d8ee70
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:63:18
    18:     0x55c28ad83f0a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h2790017aba790142
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/core/src/ops/function.rs:259:13
    19:     0x55c28ad83f0a - std::panicking::try::do_call::hd5d0fbb7d2d2d85d
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
    20:     0x55c28ad83f0a - std::panicking::try::h675520ee37b0fdf7
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
    21:     0x55c28ad83f0a - std::panic::catch_unwind::h803430ea0284ce79
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
    22:     0x55c28ad83f0a - std::rt::lang_start_internal::{{closure}}::h3a398a8154de3106
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:48
    23:     0x55c28ad83f0a - std::panicking::try::do_call::hf60f106700df94b2
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:403:40
    24:     0x55c28ad83f0a - std::panicking::try::hb2022d2bc87a9867
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panicking.rs:367:19
    25:     0x55c28ad83f0a - std::panic::catch_unwind::hbf801c9d61f0c2fb
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/panic.rs:129:14
    26:     0x55c28ad83f0a - std::rt::lang_start_internal::hdd488b91dc742b96
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:45:20
    27:     0x55c28a85d150 - std::rt::lang_start::hd2e17baffa2d57b5
                                 at /rustc/59eed8a2aac0230a8b53e89d4e99d55912ba6b35/library/std/src/rt.rs:62:5
    28:     0x55c28a85a29c - main
    29:     0x7f0a862c3fd0 - __libc_start_call_main
                                 at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
    30:     0x7f0a862c407d - __libc_start_main_impl
                                 at ./csu/../csu/libc-start.c:409:3
    31:     0x55c28a8580c5 - _start
    32:                0x0 - <unknown>

**Comment by rhdxmr** [comment]
Nice to meet you @jitendraky 
I guess you cloned the redbpf source code to local system and tried building it from the source.
Thank you for showing your interest in redbpf.

In order to build from source, first you need to initialize submodule before running cargo.
See this for more information: https://github.com/foniod/redbpf#building-from-source
And maybe you need to install some packages in your system before try building redbpf.

**Comment by rhdxmr** [comment]
@jitendraky 
Was the answer helpful and did you solve the problem?

**Comment by jitendraky** [comment]
> @jitendraky
> Was the answer helpful and did you solve the problem?

Hi Junyeong Jeong,

Thanks for your quick response and it was helpful to solve the problem.
