### ISSUE TITLE
TUTORIAL example runs failed: Can not find

### ISSUE THREAD

**Issue by wm775825** [foniod/redbpf#266]
i tried to run the example from [TUTOTIAL](https://github.com/foniod/redbpf/blob/main/TUTORIAL.md).
the error occurs at "attach_kprobe"

the recommended command is "cargo run", however, which can not run as "sudo cargo run"; so i run the execuable directly.

The error log is 
`sh-5.0$ sudo ./target/debug/ebpf
Jan 23 00:10:01.617 ERROR redbpf::btf: error on bpf_load_btf: magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 412
str_off: 412
str_len: 871
btf_total_size: 1307
[1] PTR (anon) type_id=2
[2] ENUM c_void size=1 vlen=2
        __variant1 val=0
        __variant2 val=1
[3] FUNC_PROTO (anon) return=4 args=(1 ctx)
[4] INT i32 size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[5] FUNC outer_do_sys_openat2 type_id=3 vlen != 0

Jan 23 00:10:01.618  WARN redbpf: Failed to load BTF but BTF is optional. Ignore it
thread 'main' panicked at 'error on KProbe::attach_kprobe: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:29:10
`

when i run not with sudo, the error log is:
`sh-5.0$ sudo ./ebpf
Jan 23 00:09:20.922 ERROR redbpf::btf: error on bpf_load_btf: magic: 0xeb9f
version: 1
flags: 0x0
hdr_len: 24
type_off: 0
type_len: 412
str_off: 412
str_len: 871
btf_total_size: 1307
[1] PTR (anon) type_id=2
[2] ENUM c_void size=1 vlen=2
        __variant1 val=0
        __variant2 val=1
[3] FUNC_PROTO (anon) return=4 args=(1 ctx)
[4] INT i32 size=4 bits_offset=0 nr_bits=32 encoding=SIGNED
[5] FUNC outer_do_sys_openat2 type_id=3 vlen != 0

Jan 23 00:09:20.922  WARN redbpf: Failed to load BTF but BTF is optional. Ignore it
thread 'main' panicked at 'error on KProbe::attach_kprobe: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })', src/main.rs:29:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
`

**Comment by wm775825** [comment]
The OS is ubuntu 20.04, the cargo bpf is v2.3.0, the version of llvm is 13.0.0

**Comment by wm775825** [comment]
The corresponding codes are
`
let mut loaded = Loader::load(probe_code()).expect("error on Loader::load");
    loaded
        .kprobe_mut("do_sys_openat2")
        .expect("error on Loaded::kprobe_mut")
        .attach_kprobe("do_sys_openat2", 0)
        .expect("error on KProbe::attach_kprobe");
`

**Comment by wm775825** [comment]
so, why attach_kprobe on "do_sys_openat2" runs failed? Where the reason may lie in?

**Comment by wm775825** [comment]
i have solved the problem. It is because that "do_sys_openat2" was inlined by gcc.
"do_sys_openat2" is a static C function, it may be inlined by gcc without telling you. You may not find this function via `sudo cat /boot/System.map-`uname -r` | grep do_sys_openat2`.
but this function is directly invoked by "do_sys_open", which is not a static function. And i find it via `sudo cat /boot/System.map-`uname -r` | grep do_sys_open`.

So i update the name of #[kprobe] function from "do_sys_openat2" to "do_sys_open" without further changes. 
By the way, you also need to update the name of kprobe to load in ${root_dir}/src/main.rs.

**Comment by wm775825** [comment]
In fact,  all kprobes may face this problem, which is explained at  [Kprobes documentation](https://www.kernel.org/doc/Documentation/kprobes.txt) (section Kprobes Features and Limitations).
