### ISSUE TITLE
Tutorial: error=Invalid argument when running

### ISSUE THREAD

**Issue by MarinPostma** [foniod/redbpf#280]
I was following along the tutorial and I can't make it run. I get the following error:

```
Feb 08 15:51:39.062 ERROR redbpf: error loading BPF program `do_sys_open' with bpf_load_program_xattr. ret=-1 os error=Invalid argument (os error 22): 
thread 'main' panicked at 'error on Loader::load: LoadError("do_sys_open", BPF)', src/main.rs:23:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

uname -a:
`Linux march 5.16.7-2-aarch64-ARCH #1 SMP Mon Feb 7 01:04:15 UTC 2022 aarch64 GNU/Linux`

llvm-config --version:
`13.0.0`

sudo pacman -Qqe | grep linux:
```
linux-aarch64
linux-aarch64-headers
linux-firmware
```

I am running archlinux on QEMU on my mac m1, maybe that's related?

Is there anythong else I can provide to help figuring this out?

**Comment by rhdxmr** [comment]
If this example doesn't work correctly... I guess there's some issue related to the system..

**Comment by MarinPostma** [comment]
It did not work either, here is the log:

```
2022-02-10T21:47:36.848098Z DEBUG redbpf::btf: `Pointer' type should not have a name but its name is `*mut c_void'. erase the name
2022-02-10T21:47:36.851641Z DEBUG redbpf::btf: `HashMap<u64, example_probes::vfsreadlat::VFSEvent>' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.856563Z DEBUG redbpf::btf: `PhantomData<u64>' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.860704Z DEBUG redbpf::btf: `PhantomData<example_probes::vfsreadlat::VFSEvent>' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.865366Z DEBUG redbpf::btf: `MaybeUninit<example_probes::vfsreadlat::VFSEvent>' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.869829Z DEBUG redbpf::btf: `()' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.872868Z DEBUG redbpf::btf: `ManuallyDrop<example_probes::vfsreadlat::VFSEvent>' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.877040Z DEBUG redbpf::btf: `PerfMap<example_probes::vfsreadlat::VFSEvent>' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.881052Z DEBUG redbpf::btf: `maps/pid' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.884341Z DEBUG redbpf::btf: `maps/timestamp' is an invalid name. invalid characters are substituted with underscores
2022-02-10T21:47:36.888011Z DEBUG redbpf::btf: [1] Pointer '*mut c_void' type_id=2
2022-02-10T21:47:36.890539Z DEBUG redbpf::btf: [2] Enumeration 'c_void' size=1 vlen=2
2022-02-10T21:47:36.892647Z DEBUG redbpf::btf: [3] FunctionProtocol '(anon)' ret_type_id=4 vlen=1
2022-02-10T21:47:36.895099Z DEBUG redbpf::btf: [4] Integer 'i32' size=4 encoding=SIGNED bits_offset=0 nr_bits=32
2022-02-10T21:47:36.897382Z DEBUG redbpf::btf: [5] Function 'outer_vfs_read_enter' type_id=3
2022-02-10T21:47:36.898466Z DEBUG redbpf::btf: [6] FunctionProtocol '(anon)' ret_type_id=4 vlen=1
2022-02-10T21:47:36.899583Z DEBUG redbpf::btf: [7] Function 'outer_vfs_read_exit' type_id=6
2022-02-10T21:47:36.901082Z DEBUG redbpf::btf: [8] Integer 'u8' size=1 encoding=(none) bits_offset=0 nr_bits=8
2022-02-10T21:47:36.902274Z DEBUG redbpf::btf: [9] Array '(anon)' type_id=8 index_type_id=10 nr_elems=4
2022-02-10T21:47:36.904276Z DEBUG redbpf::btf: [10] Integer '__ARRAY_SIZE_TYPE__' size=4 encoding=(none) bits_offset=0 nr_bits=32
2022-02-10T21:47:36.905663Z DEBUG redbpf::btf: [11] Variable '_license' type_id=9
2022-02-10T21:47:36.906696Z DEBUG redbpf::btf: [12] Integer 'u32' size=4 encoding=(none) bits_offset=0 nr_bits=32
2022-02-10T21:47:36.907895Z DEBUG redbpf::btf: [13] Variable '_version' type_id=12
2022-02-10T21:47:36.908991Z DEBUG redbpf::btf: [14] Structure 'HashMap<u64, example_probes::vfsreadlat::VFSEvent>' size=20 vlen=3
        'def' type_id=15 bits_offset=0
        '_k' type_id=16 bits_offset=0
        '_v' type_id=17 bits_offset=0
2022-02-10T21:47:36.911109Z DEBUG redbpf::btf: [15] Structure 'bpf_map_def' size=20 vlen=5
        'type_' type_id=12 bits_offset=0
        'key_size' type_id=12 bits_offset=32
        'value_size' type_id=12 bits_offset=64
        'max_entries' type_id=12 bits_offset=96
        'map_flags' type_id=12 bits_offset=128
2022-02-10T21:47:36.912967Z DEBUG redbpf::btf: [16] Structure 'PhantomData<u64>' size=0 vlen=0
2022-02-10T21:47:36.913413Z DEBUG redbpf::btf: [17] Structure 'PhantomData<example_probes::vfsreadlat::VFSEvent>' size=0 vlen=0
2022-02-10T21:47:36.913991Z DEBUG redbpf::btf: [18] Variable 'TIMESTAMP' type_id=14
2022-02-10T21:47:36.914529Z DEBUG redbpf::btf: [19] Union 'MaybeUninit<example_probes::vfsreadlat::VFSEvent>' size=32 vlen=2
        'uninit' type_id=20 bits_offset=0
        'value' type_id=21 bits_offset=0
2022-02-10T21:47:36.915166Z DEBUG redbpf::btf: [20] Integer '()' size=0 encoding=(none) bits_offset=0 nr_bits=0
2022-02-10T21:47:36.915717Z DEBUG redbpf::btf: [21] Structure 'ManuallyDrop<example_probes::vfsreadlat::VFSEvent>' size=32 vlen=1
        'value' type_id=22 bits_offset=0
2022-02-10T21:47:36.916561Z DEBUG redbpf::btf: [22] Structure 'VFSEvent' size=32 vlen=4
        'pid' type_id=23 bits_offset=0
        'tgid' type_id=23 bits_offset=64
        'timestamp' type_id=23 bits_offset=128
        'latency' type_id=23 bits_offset=192
2022-02-10T21:47:36.917549Z DEBUG redbpf::btf: [23] Integer 'u64' size=8 encoding=(none) bits_offset=0 nr_bits=64
2022-02-10T21:47:36.918084Z DEBUG redbpf::btf: [24] Variable 'MAP_VALUE_ALIGN_TIMESTAMP' type_id=19
2022-02-10T21:47:36.918555Z DEBUG redbpf::btf: [25] Structure 'MapBtf' size=40 vlen=2
        'key_type' type_id=23 bits_offset=0
        'value_type' type_id=22 bits_offset=64
2022-02-10T21:47:36.919093Z DEBUG redbpf::btf: [26] Variable 'MAP_BTF_TIMESTAMP' type_id=25
2022-02-10T21:47:36.919639Z DEBUG redbpf::btf: [27] Structure 'PerfMap<example_probes::vfsreadlat::VFSEvent>' size=20 vlen=2
        'def' type_id=15 bits_offset=0
        '_event' type_id=17 bits_offset=0
2022-02-10T21:47:36.920663Z DEBUG redbpf::btf: [28] Variable 'PID' type_id=27
2022-02-10T21:47:36.921100Z DEBUG redbpf::btf: [29] DataSection '.rodata' size=32 vlen=1
        type_id=24 offset=0 size=32
2022-02-10T21:47:36.921670Z DEBUG redbpf::btf: [30] DataSection 'license' size=4 vlen=1
        type_id=11 offset=0 size=4
2022-02-10T21:47:36.922069Z DEBUG redbpf::btf: [31] DataSection 'maps.ext' size=40 vlen=1
        type_id=26 offset=0 size=40
2022-02-10T21:47:36.922576Z DEBUG redbpf::btf: [32] DataSection 'maps/pid' size=20 vlen=1
        type_id=28 offset=0 size=20
2022-02-10T21:47:36.923186Z DEBUG redbpf::btf: [33] DataSection 'maps/timestamp' size=20 vlen=1
        type_id=18 offset=0 size=20
2022-02-10T21:47:36.923741Z DEBUG redbpf::btf: [34] DataSection 'version' size=4 vlen=1
        type_id=13 offset=0 size=4
2022-02-10T21:47:36.924537Z DEBUG redbpf: Map `timestamp' has BTF info. MapBtfTypeId { btf_fd: 9, key_type_id: 23, value_type_id: 22 }
2022-02-10T21:47:36.925504Z ERROR redbpf: error loading BPF program `vfs_read' with bpf_load_program_xattr. ret=-1 os error=Invalid argument (os error 22): 
thread 'main' panicked at 'error loading BPF program: LoadError("vfs_read", BPF)', examples/example-userspace/examples/vfsreadlat.rs:95:53
```

I also found this issue on bcc side: https://github.com/iovisor/bcc/issues/881, but I am not sure how to validate that
