### ISSUE TITLE
Example echo: Data sent before sockmap is ready is only sent after second message

### ISSUE THREAD

**Issue by gfokkema** [foniod/redbpf#281]
To reproduce the issue with a contrived example:
```bash
gerlof@host:redbpf $ cargo build --features llvm13
gerlof@host:redbpf $ sudo target/debug/examples/echo 10000
gerlof@host:redbpf $ (sleep .0015 ; echo test) | nc -N 127.0.0.1 10000
test
gerlof@host:redbpf $ (sleep .0015 ; echo test) | nc -N 127.0.0.1 10000
test
gerlof@host:redbpf $ (sleep .0015 ; echo test) | nc -N 127.0.0.1 10000
gerlof@host:redbpf $ (sleep .0015 ; echo test) | nc -N 127.0.0.1 10000
```

The output of echo for a failed result:
```bash
new client: 127.0.0.1:33392, fd: 15
ipv4: 7f 0 0 1 port: 0 0 82 70
delete client: 127.0.0.1:33392 fd: 15
new client: 127.0.0.1:33396, fd: 15
ipv4: 7f 0 0 1 port: 0 0 82 74
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Map', examples/example-userspace/examples/echo.rs:115:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
delete client: 127.0.0.1:33396 fd: 15
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SendError(Delete { key: IdxMapKey { addr: 16777343, port: 1954676736 } })', examples/example-userspace/examples/echo.rs:70:60
```

Keeping the connection open and sending a second message when the first reply was not sent, causes the first and second reply to be both be sent:
```bash
gerlof@host:redbpf $ (sleep .0015 ; echo test ; sleep 1 ; echo a) | nc -N 127.0.0.1 10000
test    # <-- received immediately
a       # <-- received after 1 second
gerlof@host:redbpf $ (sleep .0015 ; echo test ; sleep 1 ; echo a) | nc -N 127.0.0.1 10000
test    # <-- received after 1 second
a       # <-- received after 1 second
gerlof@host:redbpf $ (sleep .0015 ; echo test ; sleep 1 ; echo a) | nc -N 127.0.0.1 10000
test    # <-- received after 1 second
a       # <-- received after 1 second
```

Using bpftool to trace the program log, i can verify that #[sendmap_parser] is not called for the first packet in the problematic cases, but since I'm only taking a first look at redbpf I'm in no way qualified to tell what's going on here.

A less contrived example with real world use cases experiencing the same problem is `curl`... ;)

**Comment by gfokkema** [comment]
Hi there!

`nc -N` shuts down the network socket after EOF on stdin (bsd netcat vs gnu netcat or smth).

When the `echo` example misses a reply, afterwards, as soon as netcat closes the fd,
the EOF causes a second message that _does_ trigger the reply, causing the example to write to the already closed fd,
leading to a segfault (as was noted in the example).

The segfault is thus to be expected really, and the curious behaviour is why sometimes the first trigger to process the packet is missed until the second trigger comes along (either EOF or a different message such as `a`).

Ie, this intermittent behaviour:
```bash
gerlof@host:redbpf $ (sleep .0015 ; echo test; sleep 1; echo a) | nc 127.0.0.1 10000
test   # <-- received immediately
a      # <-- received after 1 second
gerlof@host:redbpf $ (sleep .0015 ; echo test; sleep 1; echo a) | nc 127.0.0.1 10000
test   # <-- received after 1 second
a      # <-- received after 1 second
gerlof@host:redbpf $ (sleep .0015 ; echo test; sleep 1; echo a) | nc 127.0.0.1 10000
test   # <-- received immediately
a      # <-- received after 1 second
```

Thank you for your response!

**Comment by rhdxmr** [comment]
@gfokkema 

I've investigated this issue recently and fix some part of the problem. But I
am still looking for a solution for that stream parser is not triggered before
the second packet is received.

**Solved issues**

1. The problem that echo program dies if nc sends packets right after the connection is established without delay.
2. The problem that nc does not get response from the echo server if nc closes connection in half right after the packet is sent without delay.

**Root cause of above problems**

1. Updating sockmap with a new socket descriptor fails if some epoll events
of the socket occurs before. To avoid this situation, change the program to
update sockmap right after the accept call finished.
2. Updating sockmap with a new socket descriptor also fails if the connection
is already half closed by peer which is nc. To avoid this situation, as a
fallback, userspace program reads data from the socket and conducts echo-ing in
person.


**Unsolved problem**

It seems that the data that is already received and stored at the TCP backlog
before setting sockmap does not trigger the stream parser. That causes the
first packet sent before setting sockmap does not lead to the echo response.

I am wondering there is a way to trigger stream parser with the existing data
in the backlog when updating sockmap.

**Comment by rhdxmr** [comment]
I forgot to attach the link of the PR that solves problems mentioned above.
Here it is: 
* #294  

I'll let you know if I find a solution for applying stream parser for the first packet that is received before sockmap setting.

**Comment by rhdxmr** [comment]
@gfokkema 

I found a workaround to trigger stream parser manually.
* #297 

Calling `setsockopt(SO_RCVLOWAT)` right after setting sockmap solves the
problem. It makes the kernel check whether tcp received data is ready so that
the packets already received before setting sockmap are processed immediately.

This PR makes the first packet is echoed instantly.
I hope this change solves the problem you had struggled with.
Thanks,

**Comment by gfokkema** [comment]
Thank you very much for your efforts, very much appreciated!

My apologies for the late reply (student life), I'll make sure to soon find some time, test your improvements and post an update here.
