### ISSUE TITLE
Cannot build examples in docker container

### ISSUE THREAD

**Issue by randomname111111111** [foniod/redbpf#314]
Host Fedora 35
Kernel 5.16.18-200.fc35.x86_64

steps to reproduce
download and unzip https://codeload.github.com/foniod/redbpf/zip/refs/tags/v2.3.0

cd redbpf-2.3.0/
$ docker run --rm -it -v ${PWD}:/build --entrypoint=/bin/bash ghcr.io/foniod/redbpf-build:latest-x86_64-fedora35 
$ cargo build --examples

````
   Compiling bpf-sys v2.3.0 (/build/bpf-sys)
error: failed to run custom build command for `bpf-sys v2.3.0 (/build/bpf-sys)`

Caused by:
  process didn't exit successfully: `/build/target/debug/build/bpf-sys-9f9909cd75b2d756/build-script-build` (exit status: 101)
  --- stdout
  cargo:rustc-link-search=native=/build/target/debug/build/bpf-sys-9d104128567b1108/out
  cargo:rustc-link-lib=static=bpf
  cargo:rustc-link-lib=elf
  cargo:rustc-link-lib=z
  cargo:rerun-if-changed=libbpf/
  cargo:rerun-if-changed=bpfsys-musl.h
  cargo:rerun-if-changed=libbpf_xdp.h

  --- stderr
  make: *** libbpf/src: No such file or directory.  Stop.
  thread 'main' panicked at 'failed to build `libbpf` static library', bpf-sys/build.rs:56:9
  stack backtrace:
     0: std::panicking::begin_panic
               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/std/src/panicking.rs:525:12
     1: build_script_build::main
               at ./build.rs:56:9
     2: core::ops::function::FnOnce::call_once
               at /rustc/db9d1b20bba1968c1ec1fc49616d4742c1725b4b/library/core/src/ops/function.rs:227:5
  note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
  ```

**Comment by nbaksalyar** [comment]
>   make: *** libbpf/src: No such file or directory.  Stop.

Unfortunately, Github zip archives don't include Git submodules. In this case, you're missing the `libbpf` submodule which you need to [download separately](https://github.com/libbpf/libbpf/tree/56794b31eea0a6245f194b5915e3ed867be144fe) and put inside the `bpf-sys/libbpf` directory.

**Comment by randomname111111111** [comment]
Thank you!
